apiVersion: batch/v1
kind: Job
metadata:
  name: hive-init-schema-db
spec:
  template:
    spec:
      containers:
      - name: hive-metastore-init
        image: "127.0.0.1:32000/hms-standalone"
        command: ["/opt/hive-metastore/bin/schematool"]
        args: ["--verbose" ,"-initSchema" , "-dbType", "mysql" , "-userName", "root",
          "-passWord", "mypass" , "-url", "jdbc:mysql://hive-metastore-db.default.svc.cluster.local:13306/metastore_db?createDatabaseIfNotExist=true&amp;useSSL=false"]
      restartPolicy: Never
  backoffLimit: 4