apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.hiveMetastoreService.name }}
spec:
  ports:
  - port: {{ .Values.hiveMetastoreService.port }}
    targetPort: {{ .Values.hiveMetastoreService.targetPort }}
  selector:
    app: {{ .Values.hiveMetastoreService.app }}