apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: maria-db-hms-statefulset
spec:
  # This specifies the name of the headless service associated with the StatefulSet. 
  # Headless services are used to control the domain of the network identity of the Pods in the StatefulSet.
  serviceName: {{ .Values.hmsMariaDBService.serviceName | quote }}
  selector:
    matchLabels:
      app: {{ .Values.hmsMariaDBService.selectorApp }}
  template:
    metadata:
      labels:
        app: {{ .Values.hmsMariaDBService.selectorApp }}
    spec:
      containers:
      - name: mariadb
        image: "mariadb:latest"
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: mypass
        ports:
        - containerPort: {{ .Values.hmsMariaDBService.targetPort }}
          name: mysql
        volumeMounts:
        - name: mariadb-for-hive
          mountPath: /var/lib/mysql
        resources:
          requests:
            memory: {{ .Values.hmsMariaResources.memory | quote }}
            cpu: {{ .Values.hmsMariaResources.cpu }}
  volumeClaimTemplates:
  - metadata:
      name: mariadb-for-hive
    spec:
      storageClassName: {{ .Values.pvcSpec.storageClassName }}
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 20Gi
