hiveMetastoreService:
  name: hive-metastore-svc
  port: 30983
  targetPort: 9083
  app: hive-metastore

hiveMetastoreSTS:
  image: 127.0.0.1:32000/hms-standalone
  resources:
    cpu: 2
    mem: 8G

configMapVol:
  volName: metastore-cfg-vol
  cfgName: metastore-cfg

pvcSpec:
  name: hms-pv-claim
  storageClassName: ssd-micron0
  accessModes: ReadWriteOnce
  storage: 20Gi