kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ .Values.hiveSparkExec.roleBind.name }}
  namespace: {{ .Values.hiveSparkExec.namespace }}
subjects:
  - kind: ServiceAccount
    name: {{ .Values.hiveSparkExec.serviceAccount.name }}
roleRef:
  kind: Role
  name: {{ .Values.hiveSparkExec.role.name }}
  apiGroup: rbac.authorization.k8s.io