hiveSparkExec:
  namespace: default
  serviceAccount:
    name: hive-spark-exec-sa
  role:
    name: hive-spark-exec-role
  roleBind:
    name: spark-rolebinding
  pvc:
    storageClass:
      name: ssd-micron0